# Surf House page copy — loaded by build.py (5 languages)
# Mandatory marketing copy + room for extra UI strings (bento captions, etc.)

SURF_HOUSE_PAGE = {
    "en": {
        "title": "Surf House on Ngor Island, Senegal | Ngor Surfcamp Teranga",
        "meta": "Welcome to Ngor Surf House: private & shared rooms, pool, meals, surf transfers and daily guiding on Ngor Island, Dakar.",
        "skip": "Skip to main content",
        "hero_kicker": "Surf House on Ngor Island, Senegal",
        "h1": "Ngor Surf House",
        "tagline": "Surfing is our Way of Life",
        "welcome_lbl": "Welcome",
        "welcome_title": "Welcome to Ngor Surf House",
        "p1": "Welcome to Ngor Surf House — your home on the waves on Ngor Island, Senegal!",
        "p2": "Tucked between turquoise water and a laid-back vibe, our surf house is more than just a place to stay: it’s a home base for surfers, travellers and ocean lovers from around the world.",
        "p3": "Right next to a city of millions, yet Ngor Island feels empty by evening — just the sound of the ocean and the glow of Dakar's lights across the water. Rooms are cleaned and beds made every day, and many offer a panoramic view of the Atlantic and the legendary Ngor Right sunset.",
        "p4": "Whether you’re a beginner or an experienced surfer, travelling solo, as a couple or with friends, our surf house offers a friendly, community-focused atmosphere — with comfortable rooms, shared living spaces, a seaside terrace, a swimming pool and easy access to some of the best surf spots in Dakar, including the world-famous wave of Ngor Island.",
        "quote_h2": "Private & shared surf rooms on Ngor Island",
        "quote_line1": "Our surf house is more than a destination",
        "quote_line2": "It’s a way of life!",
        "acc_h2": "Comfortable surf camp",
        "acc_sub": "Accommodations in Senegal",
        "meals_h2": "Enjoy local meals at our surf house in Senegal",
        "meals_p": "We’re not just sharing waves — we’re sharing moments! Enjoy generous Senegalese dishes prepared fresh every day — thiéboudienne, pastels with onion relish, grilled monkfish brochettes — breakfast and dinner included. Wash it down with café touba, the local pepper-spiced coffee that gets you revved up for the morning session.",
        "bento_h2": "Island life in pictures",
        "bento_c1": "Terrace & rooms",
        "bento_c2": "Surf spirit",
        "bento_c3": "Pool & chill",
        "bento_c4": "Senegalese table",
        "bento_c5": "Steps from the wave",
        "gal_h2": "Life at the surf house",
        "cta_h2": "Book your stay",
        "cta_p": "Rooms are cleaned and beds made every day — so you can focus on surfing. Message us on WhatsApp; we reply within 24h.",
        "book": "Book your stay",
        "copyright": "© NGOR SURFCAMP TERANGA. All rights reserved.",
        "privacy": "Privacy & information",
        "rooms_lbl": "Accommodation",
        "meals_lbl": "Kitchen & dining",
        "wa_btn": "WhatsApp",
        "pool_lbl": "Pool & Common Areas",
        "pool_h2": "Chill between sessions",
        "pool_p": "Dive into our outdoor pool at the heart of the island. Rinse off, sun-dry your board and swap stories from the lineup. The terrace is yours until the next set rolls in.",
        "pool_img_alt": "Pool at Ngor Surf House",
        "stat_island": "Island",
        "stat_from_wave": "from the wave",
        "stat_all_in": "meals · surf · guiding",
    },
    "fr": {
        "title": "Surf House à Ngor Island, Sénégal | Ngor Surfcamp Teranga",
        "meta": "Bienvenue à la Ngor Surf House : chambres privées et partagées, piscine, repas, transferts surf et guiding quotidien à Ngor, Dakar.",
        "skip": "Passer au contenu principal",
        "hero_kicker": "Surf House sur l’île de Ngor, Sénégal",
        "h1": "Ngor Surf House",
        "tagline": "Le surf, c’est notre façon de vivre",
        "welcome_lbl": "Bienvenue",
        "welcome_title": "Bienvenue à la Ngor Surf House",
        "p1": "Bienvenue à la Ngor Surf House — votre maison sur les vagues, sur l’île de Ngor au Sénégal !",
        "p2": "Nichée entre l’eau turquoise et une ambiance décontractée, notre surf house est bien plus qu’un simple hébergement : c’est votre base pour surfeurs, voyageurs et amoureux de l’océan du monde entier.",
        "p3": "Notre surf house sur l’île de Ngor offre une atmosphère chaleureuse et tournée vers la communauté, à deux pas de l’océan. Les chambres sont nettoyées et les lits faits chaque jour — nos clients la classent régulièrement comme la surf house la plus propre et la mieux entretenue de l’île. De nombreuses chambres offrent une vue panoramique sur l’Atlantique et le coucher de soleil sur Ngor Right.",
        "p4": "Que vous soyez débutant ou surfeur expérimenté, en solo, en couple ou entre amis, vous trouverez une ambiance conviviale — chambres confortables, espaces partagés, terrasse face à la mer, piscine et accès facile aux meilleurs spots de Dakar, dont la vague mythique de Ngor.",
        "quote_h2": "Chambres privées & partagées sur l’île de Ngor",
        "quote_line1": "Notre surf house est plus qu’une destination",
        "quote_line2": "C’est un mode de vie !",
        "acc_h2": "Hébergement surf confortable",
        "acc_sub": "Au Sénégal",
        "meals_h2": "Repas locaux à la surf house",
        "meals_p": "Nous ne partageons pas seulement les vagues — nous partageons des moments ! Thiéboudienne, pastels à la sauce oignon, brochettes de lotte grillées — petit-déjeuner et dîner inclus, préparés frais chaque jour. Accompagnez le tout d’un café touba, le café épicé local qui vous prépare pour la session du matin.",
        "bento_h2": "L’île en images",
        "bento_c1": "Terrasse & chambres",
        "bento_c2": "Esprit surf",
        "bento_c3": "Piscine & détente",
        "bento_c4": "Table sénégalaise",
        "bento_c5": "À deux pas de la vague",
        "gal_h2": "La vie à la surf house",
        "cta_h2": "Réservez votre séjour",
        "cta_p": "Chambres nettoyées et lits faits chaque jour — pour que vous ne pensiez qu’au surf. Écrivez-nous sur WhatsApp ; réponse sous 24h.",
        "book": "Réserver",
        "copyright": "© NGOR SURFCAMP TERANGA. Tous droits réservés.",
        "privacy": "Confidentialité & infos",
        "rooms_lbl": "Hébergement",
        "meals_lbl": "Cuisine",
        "wa_btn": "WhatsApp",
        "pool_lbl": "Piscine & Espaces Communs",
        "pool_h2": "Décompressez entre les sessions",
        "pool_p": "Plongez dans notre piscine extérieure au cœur de l'île. Rincez-vous, faites sécher votre planche et échangez les meilleures vagues du jour sur la terrasse. Elle est à vous jusqu'à la prochaine série.",
        "pool_img_alt": "Piscine à la Ngor Surf House",
        "stat_island": "Île",
        "stat_from_wave": "de la vague",
        "stat_all_in": "repas · surf · guiding",
    },
    "es": {
        "title": "Surf House en la isla de Ngor, Senegal | Ngor Surfcamp Teranga",
        "meta": "Bienvenido a Ngor Surf House: habitaciones privadas y compartidas, piscina, comidas, traslados surf y guía diaria en la isla de Ngor, Dakar.",
        "skip": "Ir al contenido principal",
        "hero_kicker": "Surf House en la isla de Ngor, Senegal",
        "h1": "Ngor Surf House",
        "tagline": "El surf es nuestra forma de vida",
        "welcome_lbl": "Bienvenida",
        "welcome_title": "Bienvenido a Ngor Surf House",
        "p1": "¡Bienvenido a Ngor Surf House, tu hogar sobre las olas en la isla de Ngor, Senegal!",
        "p2": "A cinco minutos en piragua del continente, nuestra surf house se encuentra en la isla donde se filmó The Endless Summer. Entre el agua turquesa y un ambiente relajado, es mucho más que un alojamiento: es la base de surfistas, viajeros y amantes del océano de todo el mundo.",
        "p3": "Justo al lado de una ciudad de millones de personas, la isla de Ngor se vacía al atardecer — solo queda el sonido del océano y las luces de Dakar al otro lado del agua. Las habitaciones se limpian y las camas se hacen cada día, y muchas tienen vista panorámica al Atlántico y al legendario atardecer sobre Ngor Right.",
        "p4": "Tanto si eres principiante como surfista con experiencia, si viajas solo, en pareja o con amigos, encontrarás un ambiente cercano — habitaciones cómodas, espacios compartidos, terraza frente al mar, piscina y acceso a algunos de los mejores spots de Dakar, incluida la ola mundialmente famosa de la isla de Ngor.",
        "quote_h2": "Habitaciones privadas y compartidas en la isla de Ngor",
        "quote_line1": "Nuestra surf house es más que un destino",
        "quote_line2": "¡Es una forma de vida!",
        "acc_h2": "Alojamiento surf cómodo",
        "acc_sub": "En Senegal",
        "meals_h2": "Disfruta la comida local en nuestra surf house",
        "meals_p": "No solo compartimos olas — ¡compartimos momentos! Thiéboudienne, pasteles con cebolla, brochetas de rape a la parrilla — desayuno y cena incluidos, preparados frescos cada día. Acompáñalo con un café touba, el café especiado local que te prepara para la sesión matutina.",
        "bento_h2": "La isla en imágenes",
        "bento_c1": "Terraza y habitaciones",
        "bento_c2": "Espíritu surf",
        "bento_c3": "Piscina y relax",
        "bento_c4": "Mesa senegalesa",
        "bento_c5": "A un paso de la ola",
        "gal_h2": "Vida en la surf house",
        "cta_h2": "Reserva tu estancia",
        "cta_p": "Habitaciones limpias y camas hechas cada día — para que solo pienses en surf. Escríbenos por WhatsApp; respondemos en 24h.",
        "book": "Reservar",
        "copyright": "© NGOR SURFCAMP TERANGA. Todos los derechos reservados.",
        "privacy": "Privacidad e información",
        "rooms_lbl": "Alojamiento",
        "meals_lbl": "Cocina y comidas",
        "wa_btn": "WhatsApp",
        "pool_lbl": "Piscina y zonas comunes",
        "pool_h2": "Descansa entre sesiones",
        "pool_p": "Sumérgete en nuestra piscina al aire libre en el corazón de la isla. Aclárdate, deja secar tu tabla y comparte las mejores olas del día en la terraza. Es tuya hasta que llegue la próxima serie.",
        "pool_img_alt": "Piscina en Ngor Surf House",
        "stat_island": "Isla",
        "stat_from_wave": "de la ola",
        "stat_all_in": "comidas · surf · guía",
    },
    "it": {
        "title": "Surf House a Ngor Island, Senegal | Ngor Surfcamp Teranga",
        "meta": "Benvenuti alla Ngor Surf House: camere private e condivise, piscina, pasti, transfer surf e guiding quotidiano a Ngor, Dakar.",
        "skip": "Vai al contenuto principale",
        "hero_kicker": "Surf House a Ngor Island, Senegal",
        "h1": "Ngor Surf House",
        "tagline": "Il surf è il nostro modo di vivere",
        "welcome_lbl": "Benvenuti",
        "welcome_title": "Benvenuti alla Ngor Surf House",
        "p1": "Benvenuti alla Ngor Surf House — la vostra casa sulle onde a Ngor Island, in Senegal!",
        "p2": "Tra l’acqua turchese e un’atmosfera rilassata, la nostra surf house è molto più di un soggiorno: è la base per surfisti, viaggiatori e amanti dell’oceano da tutto il mondo.",
        "p3": "La nostra surf house a Ngor offre un’atmosfera accogliente e orientata alla comunità, a due passi dall’oceano. Le camere vengono pulite e i letti rifatti ogni giorno — gli ospiti la indicano regolarmente come la surf house più pulita e meglio curata dell’isola. Molte camere hanno una vista panoramica sull’Atlantico e sul tramonto su Ngor Right.",
        "p4": "Che tu sia principiante o surfista esperto, in viaggio da solo, in coppia o con amici, troverai un ambiente amichevole — camere confortevoli, spazi condivisi, terrazza sul mare, piscina e accesso ad alcuni dei migliori spot di Dakar, inclusa la famosa onda di Ngor Island.",
        "quote_h2": "Camere private e condivise a Ngor Island",
        "quote_line1": "La nostra surf house è più di una destinazione",
        "quote_line2": "È uno stile di vita!",
        "acc_h2": "Ospitalità surf confortevole",
        "acc_sub": "In Senegal",
        "meals_h2": "Assapora i piatti locali nella nostra surf house",
        "meals_p": "Non condividiamo solo onde — condividiamo momenti! Thiéboudienne, pastels alla salsa di cipolle, spiedini di rana pescatrice alla griglia — colazione e cena incluse, preparate fresche ogni giorno. Il tutto accompagnato dal café touba, il caffè speziato locale che vi carica per la sessione mattutina.",
        "bento_h2": "L’isola in immagini",
        "bento_c1": "Terrazza e camere",
        "bento_c2": "Spirito surf",
        "bento_c3": "Piscina & relax",
        "bento_c4": "Tavola senegalese",
        "bento_c5": "Due passi dall’onda",
        "gal_h2": "Vita in surf house",
        "cta_h2": "Prenota il tuo soggiorno",
        "cta_p": "Camere pulite e letti rifatti ogni giorno — così pensi solo al surf. Scrivici su WhatsApp; rispondiamo entro 24h.",
        "book": "Prenota",
        "copyright": "© NGOR SURFCAMP TERANGA. Tutti i diritti riservati.",
        "privacy": "Privacy e informazioni",
        "rooms_lbl": "Alloggio",
        "meals_lbl": "Cucina e pasti",
        "wa_btn": "WhatsApp",
        "pool_lbl": "Piscina e spazi comuni",
        "pool_h2": "Rilassati tra le sessioni",
        "pool_p": "Tuffati nella nostra piscina all'aperto nel cuore dell'isola. Risciacquati, fai asciugare la tavola e racconta le migliori onde del giorno sulla terrazza. È tua fino alla prossima serie.",
        "pool_img_alt": "Piscina alla Ngor Surf House",
        "stat_island": "Isola",
        "stat_from_wave": "dall'onda",
        "stat_all_in": "pasti · surf · guida",
    },
    "de": {
        "title": "Surf House auf Ngor Island, Senegal | Ngor Surfcamp Teranga",
        "meta": "Willkommen im Ngor Surf House: private & geteilte Zimmer, Pool, Verpflegung, Surf-Transfers und tägliches Guiding auf Ngor, Dakar.",
        "skip": "Zum Hauptinhalt springen",
        "hero_kicker": "Surf House auf Ngor Island, Senegal",
        "h1": "Ngor Surf House",
        "tagline": "Surfen ist unsere Art zu leben",
        "welcome_lbl": "Willkommen",
        "welcome_title": "Willkommen im Ngor Surf House",
        "p1": "Willkommen im Ngor Surf House — dein Zuhause auf den Wellen auf Ngor Island, Senegal!",
        "p2": "Zwischen türkisem Wasser und entspannter Insel-Atmosphäre ist unsere Surf House mehr als eine Unterkunft: ein Basecamp für Surfer:innen, Reisende und Ozeanliebhaber aus aller Welt.",
        "p3": "Unsere Surf House auf Ngor bietet eine gemütliche, community-orientierte Atmosphäre nur wenige Schritte vom Meer. Zimmer werden täglich gereinigt und Betten gemacht — Gäste wählen sie regelmäßig zur saubersten und bestgepflegten Surf House der Insel. Viele Zimmer bieten einen Panoramablick auf den Atlantik und den Sonnenuntergang über Ngor Right.",
        "p4": "Ob Anfänger:in oder erfahrene Surfer:in, allein, zu zweit oder mit Freund:innen — du findest eine offene Community, komfortable Zimmer, gemeinsame Bereiche, eine Terrasse am Meer, einen Pool und schnellen Zugang zu einigen der besten Spots in Dakar, inklusive der weltbekannten Welle von Ngor Island.",
        "quote_h2": "Private & geteilte Surf-Zimmer auf Ngor Island",
        "quote_line1": "Unsere Surf House ist mehr als ein Reiseziel",
        "quote_line2": "Sie ist eine Lebenseinstellung!",
        "acc_h2": "Komfortables Surfcamp",
        "acc_sub": "Unterkunft in Senegal",
        "meals_h2": "Genieße lokale Küche in unserer Surf House",
        "meals_p": "Wir teilen nicht nur Wellen — wir teilen Momente! Thiéboudienne, Pastels mit Zwiebelsauce, gegrillte Seeteufel-Spieße — Frühstück und Abendessen inklusive, täglich frisch. Dazu Café Touba, der lokale Gewürzkaffee, der dich für die Morgensession aufweckt.",
        "bento_h2": "Inselleben in Bildern",
        "bento_c1": "Terrasse & Zimmer",
        "bento_c2": "Surf-Feeling",
        "bento_c3": "Pool & Chillen",
        "bento_c4": "Senegalesischer Tisch",
        "bento_c5": "Nur Schritte zur Welle",
        "gal_h2": "Leben in der Surf House",
        "cta_h2": "Jetzt buchen",
        "cta_p": "Zimmer werden täglich gereinigt und Betten gemacht — damit du dich aufs Surfen konzentrieren kannst. Schreib uns per WhatsApp; wir antworten innerhalb von 24h.",
        "book": "Buchen",
        "copyright": "© NGOR SURFCAMP TERANGA. Alle Rechte vorbehalten.",
        "privacy": "Datenschutz & Infos",
        "rooms_lbl": "Unterkunft",
        "meals_lbl": "Küche & Verpflegung",
        "wa_btn": "WhatsApp",
        "pool_lbl": "Pool & Gemeinschaftsbereiche",
        "pool_h2": "Entspannen zwischen den Sessions",
        "pool_p": "Tauche in unseren Outdoor-Pool im Herzen der Insel. Abspülen, Board trocknen lassen und die besten Wellen des Tages auf der Terrasse Revue passieren lassen. Sie gehört dir bis zum nächsten Satz.",
        "pool_img_alt": "Pool im Ngor Surf House",
        "stat_island": "Insel",
        "stat_from_wave": "zur Welle",
        "stat_all_in": "Mahlzeiten · Surf · Guiding",
    },
    "nl": {
        "title": "Surf House op Ngor Island, Senegal | Ngor Surfcamp Teranga",
        "meta": "Welkom bij Ngor Surf House: privé- en gedeelde kamers, zwembad, maaltijden, surftransfers en dagelijkse begeleiding op Ngor Island, Dakar.",
        "skip": "Ga naar hoofdinhoud",
        "hero_kicker": "Surf House op Ngor Island, Senegal",
        "h1": "Ngor Surf House",
        "tagline": "Surfen is onze manier van leven",
        "welcome_lbl": "Welkom",
        "welcome_title": "Welkom bij Ngor Surf House",
        "p1": "Welkom bij Ngor Surf House — jouw thuis op de golven op Ngor Island, Senegal!",
        "p2": "Vijf minuten met de pirogue van het vasteland, ons surfhuis staat op het eiland waar The Endless Summer werd gefilmd. Genesteld tussen turquoise water en een ontspannen vibe, is het meer dan een verblijfplaats: het is de thuisbasis voor surfers, reizigers en oceaanliefhebbers van over de hele wereld.",
        "p3": "Direct naast een miljoenenstad, maar Ngor Island is 's avonds leeg — alleen het geluid van de oceaan en Dakars lichten over het water. Kamers worden dagelijks schoongemaakt en bedden opgemaakt, en veel kamers bieden een panoramisch uitzicht over de Atlantische Oceaan en de legendarische Ngor Right-zonsondergang.",
        "p4": "Of je nu beginner bent of een ervaren surfer, solo reist, als koppel of met vrienden, ons surfhuis biedt een vriendelijke, community-gerichte sfeer — met comfortabele kamers, gedeelde leefruimtes, een terras aan zee, een zwembad en gemakkelijke toegang tot enkele van de beste surfspoots in Dakar.",
        "quote_h2": "Privé- en gedeelde surfkamers op Ngor Island",
        "quote_line1": "Ons surfhuis is meer dan een bestemming",
        "quote_line2": "Het is een manier van leven!",
        "acc_h2": "Comfortabel surfkamp",
        "acc_sub": "Accommodatie in Senegal",
        "meals_h2": "Geniet van lokale maaltijden in ons surfhuis in Senegal",
        "meals_p": "We delen niet alleen golven — we delen momenten! Thiéboudienne, pastels met uienrelish, gegrilde zeeduivel-brochettes — ontbijt en diner inbegrepen, elke dag vers bereid. Spoel het weg met café touba, de lokale kruidenkoffie die je klaarstoomt voor de ochtendsessie.",
        "bento_h2": "Eilandleven in foto's",
        "bento_c1": "Terras & kamers",
        "bento_c2": "Surfgevoel",
        "bento_c3": "Zwembad & ontspanning",
        "bento_c4": "Senegalese tafel",
        "bento_c5": "Op stap van de golf",
        "gal_h2": "Leven in het surfhuis",
        "cta_h2": "Boek je verblijf",
        "cta_p": "Kamers worden dagelijks schoongemaakt en bedden opgemaakt — zodat jij je kunt concentreren op surfen. Stuur ons een WhatsApp; we antwoorden binnen 24u.",
        "book": "Boek je verblijf",
        "copyright": "© NGOR SURFCAMP TERANGA. Alle rechten voorbehouden.",
        "privacy": "Privacy & informatie",
        "rooms_lbl": "Accommodatie",
        "meals_lbl": "Keuken & maaltijden",
        "wa_btn": "WhatsApp",
        "pool_lbl": "Zwembad & gemeenschappelijke ruimtes",
        "pool_h2": "Ontspan tussen de sessies",
        "pool_p": "Duik in ons buitenzwembad in het hart van het eiland. Spoel af, laat je board drogen en wissel de beste golven van de dag uit op het terras. Het is van jou tot de volgende set.",
        "pool_img_alt": "Zwembad bij Ngor Surf House",
        "stat_island": "Eiland",
        "stat_from_wave": "van de golf",
        "stat_all_in": "maaltijden · surf · begeleiding",
    },
    "ar": {
        "title": "بيت ركوب الأمواج في جزيرة نغور، السنغال | Ngor Surfcamp Teranga",
        "meta": "مرحباً بك في Ngor Surf House: غرف خاصة ومشتركة، مسبح، وجبات، نقل الأمواج وإرشاد يومي في جزيرة نغور، داكار.",
        "skip": "الانتقال إلى المحتوى الرئيسي",
        "hero_kicker": "بيت ركوب الأمواج في جزيرة نغور، السنغال",
        "h1": "Ngor Surf House",
        "tagline": "ركوب الأمواج أسلوب حياتنا",
        "welcome_lbl": "مرحباً",
        "welcome_title": "مرحباً في Ngor Surf House",
        "p1": "مرحباً في Ngor Surf House — منزلك على الأمواج في جزيرة نغور، السنغال!",
        "p2": "متناسق بين المياه الفيروزية وأجواء الاسترخاء، منزل الأمواج لدينا أكثر من مجرد مكان للإقامة: إنه قاعدة منزلية للمتزلجين والمسافرين وعشاق المحيط من جميع أنحاء العالم.",
        "p3": "يوفر منزل الأمواج في جزيرة نغور أجواء مريحة موجهة نحو المجتمع على بعد خطوات من المحيط. تُنظَّف الغرف وتُرتَّب الأسرة يومياً — يصنفه الضيوف باستمرار كأنظف وأفضل منزل للأمواج على الجزيرة. تتمتع كثير من الغرف بإطلالة بانورامية على المحيط الأطلسي وغروب الشمس على Ngor Right.",
        "p4": "سواء كنت مبتدئاً أو متزلجاً متمرساً، مسافراً منفرداً أو مع الشريك أو الأصدقاء، يوفر منزل الأمواج لدينا أجواء ودية موجهة نحو المجتمع — مع غرف مريحة ومساحات معيشية مشتركة وشرفة على البحر ومسبح وسهولة الوصول إلى بعض أفضل مواقع الأمواج في داكار.",
        "quote_h2": "غرف أمواج خاصة ومشتركة في جزيرة نغور",
        "quote_line1": "منزل الأمواج لدينا أكثر من مجرد وجهة",
        "quote_line2": "إنه أسلوب حياة!",
        "acc_h2": "مخيم أمواج مريح",
        "acc_sub": "إقامة في السنغال",
        "meals_h2": "استمتع بالوجبات المحلية في منزل الأمواج",
        "meals_p": "لا نتشارك الأمواج فحسب — بل نتشارك اللحظات! استمتع بأطباق وطنية سخية ولذيذة يتم تحضيرها طازجة كل يوم — الإفطار والعشاء مشمولان. نكهة من الضيافة السنغالية مع الموسيقى والطعام الجيد والأجواء الرائعة.",
        "bento_h2": "حياة الجزيرة في صور",
        "bento_c1": "الشرفة والغرف",
        "bento_c2": "روح ركوب الأمواج",
        "bento_c3": "المسبح والاسترخاء",
        "bento_c4": "المائدة السنغالية",
        "bento_c5": "على مقربة من الموجة",
        "gal_h2": "الحياة في منزل الأمواج",
        "cta_h2": "احجز إقامتك",
        "cta_p": "تُنظَّف الغرف وتُرتَّب الأسرة يومياً — حتى تتفرغ لركوب الأمواج. راسلنا على واتساب؛ نرد في غضون 24 ساعة.",
        "book": "احجز إقامتك",
        "copyright": "© NGOR SURFCAMP TERANGA. جميع الحقوق محفوظة.",
        "privacy": "الخصوصية والمعلومات",
        "rooms_lbl": "الإقامة",
        "meals_lbl": "المطبخ والوجبات",
        "wa_btn": "واتساب",
        "pool_lbl": "المسبح والمناطق المشتركة",
        "pool_h2": "استرخ بين الجلسات",
        "pool_p": "انغمس في مسبحنا الخارجي في قلب الجزيرة. اشطف نفسك، جفف لوحتك واستمتع بتبادل أجمل أمواج اليوم على الشرفة. إنها لك حتى الموجة التالية.",
        "pool_img_alt": "مسبح في Ngor Surf House",
        "stat_island": "جزيرة",
        "stat_from_wave": "من الموجة",
        "stat_all_in": "وجبات · أمواج · إرشاد",
    },
}

SURF_HOUSE_FEATS = {
    "en": [
        ("feat-rooms", "Private & shared rooms", "Single or double rooms (with or without balcony) just steps from the ocean, plus a comfortable dorm with bathroom."),
        ("feat-food", "Breakfast & dinner included", "Enjoy authentic Senegalese meals every day, plus filtered water, tea and instant coffee."),
        ("feat-transfer", "Surf transfers", "Boat transfers to surf Ngor Right & Left, and minibus transport to Dakar’s best surf spots (depending on swell)."),
        ("feat-guide", "Daily surf guiding", "We guide you to the best spot of the day, every day. All levels welcome!"),
        ("feat-theory", "Surf theory classes", "Free surf theory sessions to improve your technique: paddling, pop-up, turns & more."),
        ("feat-pool", "Pool & common areas", "Relax in our outdoor swimming pool and chill spaces in the heart of the island."),
        ("feat-wifi", "Free Wi-Fi", "Stay connected with complimentary Wi-Fi throughout the surf house."),
        ("icon-checklist", "Daily cleaning", "Rooms are cleaned and beds made every day — so you can focus on surfing."),
    ],
    "fr": [
        ("feat-rooms", "Chambres privées & partagées", "Chambres simples ou doubles (avec ou sans balcon) à deux pas de l’océan, plus un dortoir confortable avec salle de bain."),
        ("feat-food", "Petit-déjeuner & dîner inclus", "Repas sénégalais authentiques chaque jour, eau filtrée, thé et café soluble."),
        ("feat-transfer", "Transferts surf", "Bateau vers Ngor Right & Left, et minibus vers les meilleurs spots de Dakar (selon la houle)."),
        ("feat-guide", "Guiding surf quotidien", "Nous vous emmenons au meilleur spot du jour, chaque jour. Tous niveaux !"),
        ("feat-theory", "Cours de théorie surf", "Sessions gratuites : rame, pop-up, virages et lecture de vague."),
        ("feat-pool", "Piscine & espaces communs", "Piscine extérieure et coins détente au cœur de l’île."),
        ("feat-wifi", "Wi-Fi gratuit", "Connexion incluse dans toute la surf house."),
        ("icon-checklist", "Ménage quotidien", "Chambres nettoyées et lits faits chaque jour — concentrez-vous sur le surf."),
    ],
    "es": [
        ("feat-rooms", "Habitaciones privadas y compartidas", "Individuales o dobles (con o sin balcón) a pocos pasos del océano, más un dormitorio cómodo con baño."),
        ("feat-food", "Desayuno y cena incluidos", "Comidas senegalesas auténticas cada día, agua filtrada, té y café soluble."),
        ("feat-transfer", "Traslados surf", "Barco a Ngor Right y Left, y minibus a los mejores spots de Dakar (según el swell)."),
        ("feat-guide", "Guía surf diaria", "Te llevamos al mejor spot del día, cada día. ¡Todos los niveles!"),
        ("feat-theory", "Clases de teoría surf", "Sesiones gratuitas: remada, pop-up, giros y más."),
        ("feat-pool", "Piscina y zonas comunes", "Piscina al aire libre y espacios chill en el corazón de la isla."),
        ("feat-wifi", "Wi-Fi gratis", "Conexión gratuita en toda la surf house."),
        ("icon-checklist", "Limpieza diaria", "Habitaciones limpias y camas hechas cada día — tú solo piensa en surfear."),
    ],
    "it": [
        ("feat-rooms", "Camere private e condivise", "Singole o doppie (con o senza balcone) a due passi dall’oceano, più dormitorio comodo con bagno."),
        ("feat-food", "Colazione e cena incluse", "Piatti senegalesi autentici ogni giorno, acqua filtrata, tè e caffè solubile."),
        ("feat-transfer", "Transfer surf", "Barca per Ngor Right & Left e minibus verso i migliori spot di Dakar (in base al swell)."),
        ("feat-guide", "Guida surf giornaliera", "Ti portiamo al miglior spot del giorno, ogni giorno. Tutti i livelli!"),
        ("feat-theory", "Lezioni di teoria surf", "Sessioni gratuite: remata, pop-up, curve e altro."),
        ("feat-pool", "Piscina e spazi comuni", "Piscina all’aperto e zone relax nel cuore dell’isola."),
        ("feat-wifi", "Wi-Fi gratuito", "Connessione inclusa in tutta la surf house."),
        ("icon-checklist", "Pulizie giornaliere", "Camere pulite e letti rifatti ogni giorno — tu pensa solo al surf."),
    ],
    "de": [
        ("feat-rooms", "Private & geteilte Zimmer", "Einzel- oder Doppelzimmer (mit oder ohne Balkon) wenige Schritte vom Meer, plus gemütliches Schlafsaal mit Bad."),
        ("feat-food", "Frühstück & Abendessen inklusive", "Authentische senegalesische Mahlzeiten täglich, gefiltertes Wasser, Tee und Instantkaffee."),
        ("feat-transfer", "Surf-Transfers", "Boot zu Ngor Right & Left und Minibus zu Dakars besten Spots (je nach Swell)."),
        ("feat-guide", "Tägliches Surf-Guiding", "Wir bringen dich jeden Tag zum besten Spot des Tages. Alle Level!"),
        ("feat-theory", "Surf-Theoriekurse", "Kostenlose Sessions: Paddeln, Pop-up, Turns und mehr."),
        ("feat-pool", "Pool & Gemeinschaftsbereiche", "Outdoor-Pool und Chill-Bereiche im Herzen der Insel."),
        ("feat-wifi", "Kostenloses WLAN", "WLAN in der gesamten Surf House."),
        ("icon-checklist", "Tägliche Reinigung", "Zimmer werden gereinigt und Betten gemacht — du konzentrierst dich aufs Surfen."),
    ],
    "nl": [
        ("feat-rooms", "Privé- en gedeelde kamers", "Eenpersoons- of tweepersoonskamers (met of zonder balkon) op loopafstand van de oceaan, plus een comfortabele slaapzaal met badkamer."),
        ("feat-food", "Ontbijt & diner inbegrepen", "Elke dag authentieke Senegalese maaltijden, gefilterd water, thee en oploskoffie."),
        ("feat-transfer", "Surftransfers", "Boottransfers naar Ngor Right & Left, en minibusvervoer naar Dakars beste surfspoots (afhankelijk van swell)."),
        ("feat-guide", "Dagelijkse surfbegeleiding", "We begeleiden je elke dag naar de beste spot van de dag. Alle niveaus welkom!"),
        ("feat-theory", "Surftheorieklassen", "Gratis sessies: peddelen, opstaan, turns en meer."),
        ("feat-pool", "Zwembad & gemeenschappelijke ruimtes", "Ontspan in ons buitenzwembad en chill-zones in het hart van het eiland."),
        ("feat-wifi", "Gratis Wi-Fi", "Verbinding inbegrepen in het hele surfhuis."),
        ("icon-checklist", "Dagelijkse schoonmaak", "Kamers worden schoongemaakt en bedden opgemaakt — zodat jij je kunt focussen op surfen."),
    ],
    "ar": [
        ("feat-rooms", "غرف خاصة ومشتركة", "غرف فردية أو مزدوجة (مع أو بدون شرفة) على بعد خطوات من المحيط، بالإضافة إلى غرفة نوم مريحة مشتركة مع حمام."),
        ("feat-food", "الإفطار والعشاء مشمولان", "وجبات سنغالية أصيلة كل يوم، مياه مفلترة، شاي وقهوة فورية."),
        ("feat-transfer", "نقل الأمواج", "نقل بالقارب إلى Ngor Right وLeft، وحافلة صغيرة إلى أفضل مواقع داكار (حسب السويل)."),
        ("feat-guide", "إرشاد يومي للأمواج", "نرشدك كل يوم إلى أفضل موقع في اليوم. جميع المستويات مرحب بها!"),
        ("feat-theory", "دروس نظرية في ركوب الأمواج", "جلسات مجانية: التجديف، الوقوف، المنعطفات والمزيد."),
        ("feat-pool", "المسبح والمناطق المشتركة", "استرخِ في مسبحنا الخارجي ومناطق الاسترخاء في قلب الجزيرة."),
        ("feat-wifi", "واي فاي مجاني", "اتصال مجاني في جميع أنحاء منزل الأمواج."),
        ("icon-checklist", "تنظيف يومي", "تُنظَّف الغرف وتُرتَّب الأسرة يومياً — حتى تتفرغ لركوب الأمواج."),
    ],
}

# PT/DA fallback entries
SURF_HOUSE_PAGE["pt"] = dict(SURF_HOUSE_PAGE["es"])
SURF_HOUSE_PAGE["pt"].update({
    "title": "Casa de Surf | Ngor Surfcamp Teranga",
    "meta": "A casa de surf no coração da Ilha de Ngor — quartos com vista para o mar, refeições senegalesesas, piscina e um ambiente perfeito para surfistas.",
    "h1": "Surf House",
    "sub": "A nossa casa de surf fica no coração da Ilha de Ngor — sem carros, sem ruído, apenas o Atlântico.",
})
SURF_HOUSE_PAGE["da"] = dict(SURF_HOUSE_PAGE["de"])
SURF_HOUSE_PAGE["da"].update({
    "title": "Surf House | Ngor Surfcamp Teranga",
    "meta": "Surf house i hjertet af Ngor Island — havudsigtsværelser, senegalesiske måltider, pool og den perfekte stemning for surfere.",
    "h1": "Surf House",
    "sub": "Vores surf house ligger i hjertet af Ngor Island — ingen biler, ingen støj, kun Atlanterhavet.",
})
SURF_HOUSE_FEATS["pt"] = list(SURF_HOUSE_FEATS["es"])
SURF_HOUSE_FEATS["da"] = list(SURF_HOUSE_FEATS["de"])
